spring:
  profiles:
    active: nacosTest
  application:
    name: nacos-provide
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}
        file-extension: yml
        group: ${spring.application.name}
        extension-configs[0]:
          data-id: nacos-provide-${spring.profiles.active}.yml
          group: ${spring.application.name}
          refresh: true
      discovery:
        enable: true
        register-enabled: true
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.profiles.active}
        group: ${spring.profiles.active}
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update #新增数据库连接必备的参数
      show-sql: true  #日志中显示sql语句
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8    # 连接池中的最大空闲连接 默认 8
        min-idle: 0    # 连接池中的最小空闲连接 默认 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_emp?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      max-wait: 50000
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: false
dubbo:
  application:
    id: nacos-provide-dubbo
    name: nacos-provide-dubbo
  registry:
    address: nacos://${spring.cloud.nacos.config.server-addr}?namespace=${spring.profiles.active}
  protocol:
    name: dubbo
    port: 27801
  scan:
    base-packages: springbootdemo
  consumer:
    retries: 0
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
name: 张三
age: 22
student:
  name: 李四
  age: 23
